# Generated by Django 3.0.9 on 2020-08-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0004_passowrd_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passowrd',
            new_name='Password',
        ),
    ]
