# Generated by Django 3.0.9 on 2020-08-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0006_topic_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
