# Generated by Django 3.0.9 on 2020-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0007_topic_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='send_email',
            field=models.BooleanField(default=True),
        ),
    ]
