# Generated by Django 3.0.9 on 2020-09-04 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spirit_topic', '0008_auto_20200830_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='follow',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
