# Generated by Django 3.0.9 on 2020-09-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0005_comment_anonymous'),
        ('spirit_topic_notification', '0003_notificationoftopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicnotification',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spirit_comment.Comment'),
        ),
    ]
