# Generated by Django 3.0.9 on 2020-09-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic_notification', '0004_auto_20200907_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationOfTopic',
        ),
    ]
