# Generated by Django 3.0.9 on 2020-09-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic_notification', '0006_auto_20200907_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicnotification',
            name='action',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Mention'), (2, 'Comment'), (3, 'Topic')], default=0),
        ),
    ]
