# Generated by Django 3.0.9 on 2020-09-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic_notification', '0007_auto_20200908_0504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topicnotification',
            unique_together=set(),
        ),
    ]
