# Generated by Django 3.0.9 on 2020-08-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0004_auto_20160315_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
