# Generated by Django 3.0.9 on 2020-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0011_auto_20181124_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_send',
            field=models.CharField(blank=True, choices=[('Email when Moderator Publish', 'Email on Every Publish'), ('Email when Moderator Publish', 'Email on Every Publish')], max_length=50, null=True),
        ),
    ]
