# Generated by Django 3.0.9 on 2020-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0012_userprofile_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_send',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
