# Generated by Django 3.0.9 on 2020-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0013_auto_20200830_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_send',
            field=models.CharField(blank=True, default='2', max_length=50, null=True),
        ),
    ]
